version: '3.2'

services:

  backend:
    build:
      context: ./services/backend
      dockerfile: Dockerfile.prod
    restart: always
    ports:
      - 5001:5000
    environment:
      - DEFAULT_COMPANY_NAME
      - FLASK_ENV=${ENVIRONMENT}

      - DATABASE_URL=postgresql://postgres:postgres@db:5432/app_prod
      - DATABASE_TEST_URL=postgresql://postgres:postgres@db:5432/app_test

      - MAIL_SERVER
      - MAIL_USERNAME
      - MAIL_PASSWORD

      - CLOUDINARY_CLOUD_NAME
      - CLOUDINARY_API_KEY
      - CLOUDINARY_API_SECRET

      - SECRET_KEY

      - APP_SETTINGS=app.config.ProductionConfig
    depends_on:
      - db

  db:
    build:
      context: ./services/db
      dockerfile: Dockerfile
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD

  frontend:
    build:
      context: ./services/frontend
      dockerfile: Dockerfile.prod
      args:
        - NODE_ENV=production
        - CHOKIDAR_USEPOLLING=true
        - REACT_APP_BACKEND_SERVICE_URL

        - REACT_APP_GOOGLE_API_KEY
        - REACT_APP_GEOAPIFY_API_KEY
        - REACT_APP_BACKEND_SERVICE_URL=http://localhost:5001
    restart: always
    ports:
      - 3007:80
    depends_on:
      - backend
